CRITICAL - 2021-02-23 00:11:33 --> Call to undefined function vies()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('index', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('index')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 01:42:26 --> syntax error, unexpected '<', expecting end of file
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('home', Array, true)
#2 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('home')
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-23 03:31:10 --> Invalid file: foteer.php
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('foteer.php')
#1 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('foteer', Array, true)
#2 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(11): view('foteer')
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-23 03:46:40 --> Class 'App\libraries\AuthLibrary' not found
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 03:47:41 --> Class 'App\libraries\AuthLibrary' not found
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 03:47:42 --> Class 'App\libraries\AuthLibrary' not found
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 03:49:35 --> Class 'App\libraries\AuthLibrary' not found
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 03:53:58 --> Class 'App\libraries\AuthLibrary' not found
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 03:55:56 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(142): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:04:57 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(142): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:06:44 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(142): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:06:52 --> Call to undefined function App\libraries\get_cookie()
#0 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-23 04:07:31 --> Call to undefined function App\libraries\get_cookie()
#0 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-23 04:09:08 --> Call to undefined function App\libraries\get_cookie()
#0 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-23 04:09:29 --> Call to undefined function App\libraries\get_cookie()
#0 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-23 04:10:29 --> Call to undefined function App\libraries\get_cookie()
#0 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-23 04:12:11 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:12:20 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:13:14 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:15:40 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:15:52 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:16:32 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:16:52 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:17:05 --> Call to undefined function set_value()
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/register', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(144): view('user/register')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 04:47:08 --> Недопустимый файл: templates/header.php
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('templates/heade...')
#1 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('templates/heade...', Array, true)
#2 D:\xampp\htdocs\emlog.loc\app\Controllers\Dashboard.php(26): view('templates/heade...', Array)
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Dashboard->index()
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-23 04:47:16 --> Недопустимый файл: templates/header.php
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('templates/heade...')
#1 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('templates/heade...', Array, true)
#2 D:\xampp\htdocs\emlog.loc\app\Controllers\Dashboard.php(26): view('templates/heade...', Array)
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Dashboard->index()
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-23 04:48:00 --> Недопустимый файл: user/dashboard.php
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/dashboard....')
#1 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/dashboard', Array, true)
#2 D:\xampp\htdocs\emlog.loc\app\Controllers\Dashboard.php(27): view('user/dashboard')
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Dashboard->index()
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-23 05:33:04 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:33:12 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:33:17 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:42:35 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:42:43 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:42:44 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:43:35 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:44:23 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:44:38 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:45:11 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:45:12 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:45:13 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(162): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '835dc7201be2')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '835dc7201be2')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 05:55:14 --> Toolbar collector does not exists(CodeIgniter\Debug\Toolbar\Collectors\Cache).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 05:55:19 --> Toolbar collector does not exists(CodeIgniter\Debug\Toolbar\Collectors\Cache).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 06:05:11 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:05:18 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:05:37 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:05:38 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:05:38 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:06:08 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:06:09 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:06:38 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:07:17 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:07:17 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:07:18 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:07:27 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 06:08:24 --> Call to a member function getSegment() on null
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#3 D:\xampp\htdocs\emlog.loc\app\Controllers\Home.php(9): view('header')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Home->index()
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 07:22:37 --> Недопустимый файл: user/setting.php
#0 D:\xampp\htdocs\emlog.loc\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/setting.ph...')
#1 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('user/setting', Array, true)
#2 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(241): view('user/setting')
#3 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->profile()
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-23 07:25:12 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:25:26 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:25:30 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:25:33 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:25:37 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:25:41 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:26:05 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:31:52 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:31:57 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:31:58 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:32:01 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:32:05 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:32:08 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:37:01 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:37:18 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:44:52 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:45:23 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:46:45 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:47:08 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:48:39 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:48:41 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:48:55 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:49:03 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:49:24 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:49:25 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:50:10 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:50:57 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:51:27 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:53:08 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:53:09 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:53:22 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:53:32 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:53:39 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 07:53:46 --> Toolbar collector does not exists(App\Collectors\Auth).please check $collectors in the Config\Toolbar.php file.
CRITICAL - 2021-02-23 09:19:32 --> Too few arguments to function service(), 0 passed in D:\xampp\htdocs\emlog.loc\app\Views\header.php on line 16 and exactly 1 expected
#0 D:\xampp\htdocs\emlog.loc\app\Views\header.php(16): service()
#1 D:\xampp\htdocs\emlog.loc\system\View\View.php(220): include('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\emlog.loc\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 D:\xampp\htdocs\emlog.loc\system\Common.php(1257): CodeIgniter\View\View->render('header', Array, true)
#4 D:\xampp\htdocs\emlog.loc\app\Controllers\Profile.php(12): view('header', Array)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Profile->index()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-02-23 10:28:49 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(147): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '308688b00951')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '308688b00951')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 10:28:53 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(147): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, '308688b00951')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', '308688b00951')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 10:29:28 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(147): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, 'aab1f3b556af')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', 'aab1f3b556af')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 10:29:31 --> Нет данных в update.
#0 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(1677): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 D:\xampp\htdocs\emlog.loc\system\BaseModel.php(864): CodeIgniter\BaseModel->transformDataToArray(NULL, 'update')
#2 D:\xampp\htdocs\emlog.loc\system\Model.php(737): CodeIgniter\BaseModel->update(Array, NULL)
#3 D:\xampp\htdocs\emlog.loc\app\Models\AuthModel.php(147): CodeIgniter\Model->update(Array)
#4 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(795): App\Models\AuthModel->UpdateSelector(Array, 'aab1f3b556af')
#5 D:\xampp\htdocs\emlog.loc\app\Libraries\AuthLibrary.php(748): App\libraries\AuthLibrary->rememberMeReset('1', 'aab1f3b556af')
#6 D:\xampp\htdocs\emlog.loc\app\Controllers\Auth.php(42): App\libraries\AuthLibrary->checkCookie()
#7 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#8 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-23 15:52:37 --> syntax error, unexpected 'exit' (T_EXIT)
#0 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 15:52:45 --> syntax error, unexpected 'exit' (T_EXIT)
#0 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 15:53:10 --> Call to undefined method App\libraries\AuthLibrary::check()
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 15:53:11 --> Call to undefined method App\libraries\AuthLibrary::check()
#0 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#1 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-02-23 15:53:31 --> syntax error, unexpected ')'
#0 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 15:53:32 --> syntax error, unexpected ')'
#0 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 15:53:40 --> syntax error, unexpected ')'
#0 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-23 15:53:40 --> syntax error, unexpected ')'
#0 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\emlog.loc\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\emlog.loc\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-02-23 22:27:18 --> mysqli_sql_exception: Table 'users' already exists in D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php:329
Stack trace:
#0 D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php(329): mysqli->query('CREATE TABLE `u...')
#1 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 D:\xampp\htdocs\emlog.loc\system\Database\Forge.php(525): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 D:\xampp\htdocs\emlog.loc\app\Database\Migrations\2021-24-02-000002_users_add_password.php(21): CodeIgniter\Database\Forge->createTable('users')
#5 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(1057): App\Database\Migrations\Users->up()
#6 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(202): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\xampp\htdocs\emlog.loc\system\Commands\Database\Migrate.php(94): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\xampp\htdocs\emlog.loc\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#12 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\xampp\htdocs\emlog.loc\system\CLI\Console.php(61): CodeIgniter\CodeIgniter->run()
#15 D:\xampp\htdocs\emlog.loc\spark(66): CodeIgniter\CLI\Console->run()
#16 {main}
CRITICAL - 2021-02-23 22:35:44 --> Cannot declare class App\Database\Migrations\Users, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-02-23 22:46:36 --> mysqli_sql_exception: Too big precision 250 specified for 'password'. Maximum is 6 in D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php:329
Stack trace:
#0 D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php(329): mysqli->query('CREATE TABLE `u...')
#1 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 D:\xampp\htdocs\emlog.loc\system\Database\Forge.php(525): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 D:\xampp\htdocs\emlog.loc\app\Database\Migrations\2021-24-02-000001_add_users.php(67): CodeIgniter\Database\Forge->createTable('users')
#5 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(1057): App\Database\Migrations\Users->up()
#6 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(202): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\xampp\htdocs\emlog.loc\system\Commands\Database\Migrate.php(94): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\xampp\htdocs\emlog.loc\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#12 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\xampp\htdocs\emlog.loc\system\CLI\Console.php(61): CodeIgniter\CodeIgniter->run()
#15 D:\xampp\htdocs\emlog.loc\spark(66): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2021-02-23 22:46:52 --> mysqli_sql_exception: Too big precision 250 specified for 'password'. Maximum is 6 in D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php:329
Stack trace:
#0 D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php(329): mysqli->query('CREATE TABLE `u...')
#1 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 D:\xampp\htdocs\emlog.loc\system\Database\Forge.php(525): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 D:\xampp\htdocs\emlog.loc\app\Database\Migrations\2021-24-02-000001_add_users.php(67): CodeIgniter\Database\Forge->createTable('users')
#5 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(1057): App\Database\Migrations\Users->up()
#6 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(202): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\xampp\htdocs\emlog.loc\system\Commands\Database\Migrate.php(94): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\xampp\htdocs\emlog.loc\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#12 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\xampp\htdocs\emlog.loc\system\CLI\Console.php(61): CodeIgniter\CodeIgniter->run()
#15 D:\xampp\htdocs\emlog.loc\spark(66): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2021-02-23 22:48:00 --> mysqli_sql_exception: Too big precision 250 specified for 'password'. Maximum is 6 in D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php:329
Stack trace:
#0 D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php(329): mysqli->query('CREATE TABLE `u...')
#1 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 D:\xampp\htdocs\emlog.loc\system\Database\Forge.php(525): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 D:\xampp\htdocs\emlog.loc\app\Database\Migrations\2021-24-02-000001_add_users.php(67): CodeIgniter\Database\Forge->createTable('users')
#5 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(1057): App\Database\Migrations\Users->up()
#6 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(202): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\xampp\htdocs\emlog.loc\system\Commands\Database\Migrate.php(94): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\xampp\htdocs\emlog.loc\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#12 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\xampp\htdocs\emlog.loc\system\CLI\Console.php(61): CodeIgniter\CodeIgniter->run()
#15 D:\xampp\htdocs\emlog.loc\spark(66): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2021-02-23 23:54:57 --> mysqli_sql_exception: Invalid default value for 'created_at' in D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php:329
Stack trace:
#0 D:\xampp\htdocs\emlog.loc\system\Database\MySQLi\Connection.php(329): mysqli->query('CREATE TABLE IF...')
#1 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE IF...')
#2 D:\xampp\htdocs\emlog.loc\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE IF...')
#3 D:\xampp\htdocs\emlog.loc\system\Database\Forge.php(525): CodeIgniter\Database\BaseConnection->query('CREATE TABLE IF...')
#4 D:\xampp\htdocs\emlog.loc\app\Database\Migrations\2021-02-23-000001_create_tables.php(34): CodeIgniter\Database\Forge->createTable('users', true)
#5 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(1057): App\Database\Migrations\CreateAuthTables->up()
#6 D:\xampp\htdocs\emlog.loc\system\Database\MigrationRunner.php(202): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\xampp\htdocs\emlog.loc\system\Commands\Database\Migrate.php(94): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\xampp\htdocs\emlog.loc\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\xampp\htdocs\emlog.loc\system\CLI\CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#12 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\xampp\htdocs\emlog.loc\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\xampp\htdocs\emlog.loc\system\CLI\Console.php(61): CodeIgniter\CodeIgniter->run()
#15 D:\xampp\htdocs\emlog.loc\spark(66): CodeIgniter\CLI\Console->run()
#16 {main}
